name: KillCount
main: SuperXingKong\KillCount
author: SuperXingKong
version: 1.0.0
api: [1.0.0]
load: POSTWORLD
description: "show players' KillCount!"
commands:
 mykc:
  description: "查询你的人头数"
  usage: "/mykc"
  permission: true
 kc:
  description: "查询玩家的人头数"
  usage: "/kc [玩家名]"
  permission: true