name: KillCount
main: SuperXingKong\KillCount
author: SuperXingKong
version: Build1.2.0
api: [1.0.0]
load: POSTWORLD
description: "show players' KillCount!"
commands:
 mykc:
  description: "查询你的人头数"
  usage: "/mykc"
 kc:
  description: "查询玩家的人头数"
  usage: "/kc <玩家名>"
 url:
  description: "展示插件核服务器信息"
  usage: "/url"
  permission: op
 setkillmoney:
  description: "set the number of money that players can get when they kill others"
  usage: "/setkillmoney <money>"
  permission: op
